name: 'Maven Release by File Action'
description: 'Complete environment configuration for Maven Release by File Action'

##
## Automates the release process
## 1. Create new branch
## 2. Edit `.github/project.yml`
## 3. Create PR, merge PR
##

branding:
  icon: 'settings'
  color: 'green'

inputs:
  gpg-secret-key:
    description: "GPG secret key"
    required: true
  gpg-passphrase:
    description: "GPG passphrase"
    required: true
  ossrh-username:
    description: "OSSRH username"
    required: true
  ossrh-password:
    description: "OSSRH password"
    required: true
  github-token:
    description: "GitHub token"
    required: true
    
runs:
  using: 'composite'

  steps:
    - name: Retrieve Project Metadata
      uses: radcortez/project-metadata-action@1.2
      id: metadata
      with:
        github-token: ${{ inputs.github-token }}
        metadata-file-path: '.github/project.yml'

    - name: Set environment variables
      shell: bash
      run: |
        echo "RELEASE_VERSION=${{ steps.metadata.outputs.release-version }}" >> $GITHUB_ENV
        echo "NEXT_VERSION=${{ steps.metadata.outputs.next-version }}" >> $GITHUB_ENV

    - name: Validate release version
      if: contains(env.RELEASE_VERSION, 'SNAPSHOT')
      shell: bash  
      run: |
        echo '::error::Cannot release a SNAPSHOT version.'
        exit 1
        
    - name: Checkout Source
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}

    - name: Set up Java 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ inputs.gpg-secret-key }} # macOS: gpg --armor --export-secret-key

    - name: Configure Git User
      shell: bash
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

    - name: Set Release version
      shell: bash
      run: |
        git checkout -b "release-$RELEASE_VERSION"

        mvn versions:set -DprocessAllModules=true -DgenerateBackupPoms=false -DnewVersion=${RELEASE_VERSION}
        sed -i "s|<version>[0-9]\+\.[0-9]\+\.[0-9]\+</version>|<version>${RELEASE_VERSION}</version>|g" README.md
        git commit --no-verify -a -m "[CI Skip] Releasing branch ${RELEASE_VERSION}"

        git push origin "$RELEASE_VERSION"

    - name: Deploy to Maven Central
      shell: bash
      run: |
        mvn -B -U -ntp deploy site site:stage -DskipTests -Pcentral
      env:
        MAVEN_USERNAME: ${{ inputs.ossrh-username }}
        MAVEN_PASSWORD: ${{ inputs.ossrh-password }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}

    - name: Create Tag
      shell: bash
      run: |
        git tag -a "v${RELEASE_VERSION}" -m "Release v${RELEASE_VERSION}"
        git push --tags

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ./target/staging

    - name: Create GitHub Release
      shell: bash
      run: |
        gh release create v${RELEASE_VERSION} --generate-notes target/*.asc target/*.jar target/*.pom
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Set Next Version
      shell: bash
      run: |
        mvn versions:set -DprocessAllModules=true -DgenerateBackupPoms=false -DnewVersion=${NEXT_VERSION}
        git commit --no-verify -a -m "[CI Skip] Next version v${NEXT_VERSION}"
        git checkout $GITHUB_REF_NAME
        git branch -D "$RELEASE_VERSION"
          
    - name: Release Milestone
      uses: rosestack/milestone-release-action@main
      with:
        github-token: ${{ inputs.github-token }}
        milestone-title: ${{ env.RELEASE_VERSION }}
        milestone-next: ${{ env.NEXT_VERSION }}
