name: Maven Release by File

on:
  push:
    paths:
      - '.github/project.yml'
    branches:
      - main
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Release Maven Project
        uses: rosestack/maven-release-by-file-action@main
        with:
          working-directory: 'test-project'
          # Maven Central Authentication (Required)
          maven-username: ${{ secrets.MAVEN_USERNAME }}
          maven-password: ${{ secrets.MAVEN_PASSWORD }}
          
          # GPG Signing (Required)
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          
          # GitHub Configuration (Required)
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Optional: Java Configuration
          # java-version: '17'
          # java-distribution: 'temurin'
          
          # Optional: Maven Configuration
          # maven-args: '-B -U -ntp'
          # maven-profiles: 'central'
          # maven-server-id: 'central'
          
          # Optional: Build Options
          # skip-tests: 'false'
          # deploy-pages: 'true'
          
          # Optional: Advanced Options
          # working-directory: '.'
          # metadata-file-path: '.github/project.yml'

